---
title: "Ecological Detective - Chapter 4"
author: "Seba Tapia"
date: "7/2/2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vcdExtra)
library(dplyr)
library(data.table)
```

#load dataframes
```{r load dataframes}
SummaryData <- read.csv("/Users/seba/github/eco_detective/ch_4/data/table_4_2.csv")
colnames(SummaryData) <- c("Dates", "TowsObserved", "ByCatch", "Capture rate (birds/tow)")
SummaryData <- SummaryData[-c(1,8),]
SummaryData <- apply(SummaryData,2,as.numeric)
SummaryData <- as.data.frame(SummaryData)

FrequencyData <- read.csv("/Users/seba/github/eco_detective/ch_4/data/table_4_3.csv")
ExpandedData <- expand.dft(FrequencyData, var.names="bycatch", freq="frequency")
```

#A Montecarlo approach for estimating chance of success in observer program
# Pseudocode 4.2 Step 1
```{r pseudocode 4.2 step 1}
#First, got to calculate m and k from last year's data

m <- (1 / nrow(ExpandedData))*sum(ExpandedData$bycatch) #Equation 4.1
SampleVar <- (1 / (nrow(ExpandedData)-1))*sum((ExpandedData$bycatch - m)^2) #Equation 4.2 for the sample variance needed for k
k <- (m^2)/(SampleVar-m)  #Equation 4.8 to find k (number of successes??)

#Then set some parameters for starters
d <- 0.15  #Tolerable error of the mean (ceq 4.5)
Ntow <- 3000 #Number of tows per simulation
nsims  <- 300 #Number of simulations
  
  #((SampleVar)/(d^2))*(1.96^2)  #Equation 4.6 to find required level of observer coverage
  #((sqrt(SampleVar))/(sqrt(nrow(ExpandedData))))*1.96  #eqaution 4.5 to find tolerable error of mean

tq <- 1.96 #t-value at 95% CI
TowVec <- seq(from=1, to=Ntow, by=1) #Vector of tows
cvec <- seq(0,50, by=1)  #Vector of catches from 0 to 5
Uvec <- vector(length=length(TowVec))  #Empty vector for storing "U" (random value between 0 and 1) for each tow

SimMean <- vector(length=length(nsims))
SimVar <- vector(length=length(nsims))
SimRange   <- vector(length=length(nsims))
#Empty vectors for the mean, variance and range of each simulation
```

##Step 2-5
```{r Step 2}
#First, set up the probability calculation for a given bycatch level on the ith tow, then calculate cumulative probability for up to a level of bycatch

PByCatch <- function(c=cvec, k=k, m=m){

Term1 <- (gamma(k+c))/(gamma(k)*factorial(c))
Term2 <- ((k)/(k+m))^k
Term3 <-  ((m)/(m+k))^c
p <- Term1 * Term2 * Term3
CumP <- cumsum(p)
CumPFloor <- lag(CumP, default=0)
CumPDF <- data.frame(c,p,CumP, CumPFloor)
write.csv(CumPDF, "ByCatchProb.csv")
plot(x=c, y=p, xlab="Birds in bycatch", ylab="Probabililty")
plot(x=c, y=CumP,  xlab="Birds in bycatch", ylab="Cummulative P")}
PByCatch(c=cvec,k=k,m=m) #Store a csv with trobability of having c Birds in a net (p) and c or less birds in a net (cumP)

CumPdf <- read.csv("~/github/eco_detective/ch_4/ByCatchProb.csv")[ ,2:5] #Load said csv

#now, make a loop that for each tow draws a random uniform number and store it as UVec

for(i in TowVec){
  Uvec[i] <- runif(n=1,min=0,max=1)
}

Uvec <- data.frame(Uvec)

#Let's see where "U lies in our cummulative probability distribution". Give every U a catch value, based on the cumullative probability distribution


setkey(setDT(CumPdf), CumP) #sets Cum P as reference point
x <- CumPdf[Uvec, roll="nearest"] #joins Uvec and CumPDF and finds the nearest value, stores catch in c
SimByCatch <- x$c
hist(SimByCatch)  #draw and histogram to make sure the output makes sense

  
nsuccess <- 0

SimMean <- mean(SimByCatch)
SimVar  <- (1/(Ntow=1))*(sum(SimByCatch-SimMean)^2)
Range    <- 2*((sqrt(SimVar))/(sqrt(Ntow)))*1.96
if (Range<d) {
  nsuccess <- nsuccess+1
}
nsuccess
```

#Step 6 Iterating over sims: many failed attemptes
```{r eval=FALSE}

U <- vector(length=length(Ntow))
C <- vector(length=length(Ntow))

for(i in TowVec){
  U[i] <- runif(n=1,min=0,max=1)
  cat('i = ', i,' U = ', U, 'x=',C)
  
  C[i] <- CumPdf$c[which(U <= CumPdf$CumP & U>= CumPdf$CumPFloor)] #joins Uvec and CumPDF and finds the nearest value, stores catch in c
  SimData <- data.frame(U,C)
}
}
#Uvec <- data.frame(Uvec)

#Let's see where "U lies in our cummulative probability distribution". Give every U a catch value, based on the cumullative probability distribution
#SimDF <- matrix(data=NA, nrow=Ntow, ncol=5)


setkey(setDT(CumPdf), CumP) #sets Cum P as reference point
x <- CumPdf[Uvec, roll="nearest"] #joins Uvec and CumPDF and finds the nearest value, stores catch in c
SimByCatch <- x$c
hist(SimByCatch)  #draw and histogram to make sure the output makes sense

  
nsuccess <- 0
CompMean <- NA
CompVar <- NA
Range <- NA

function()




SimMean <- mean(SimByCatch)
SimVar  <- (1/(Ntow=1))*(sum(SimByCatch-SimMean)^2)
Range    <- 2*((sqrt(SimVar))/(sqrt(Ntow)))*1.96

cat('i = ', i, ' U = ', Uvec[i], 'Mean = ', CompMean, 'Var=', CompVar, 'Range=', Range)

if (Range<d) {
  nsuccess <- nsuccess+1
}


#for (b in seq(0,12,by=1)){
  
  #Pc <- vector(length = length(c), "numeric")
   #cat('i = ', i, ' P = ', Pc)
  #Pc[b] <- PByCatch(c=b[i], k=k, m=m)
  
#}
  

```

```