---
title: "Ch5_STL"
author: "Seba Tapia"
date: "7/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
```

#Chapter 5

#Pseudocode 5.1
##Finding the lowest SS for each parameter separately (keeping all others constant)
```{r Pseudocode 5.1}

#Step one. Input data, range of parameter va;ies and increment size

Chap5Data <- data.frame(x=c(1,2,3,4,5,6,7,8,9,10), Yobs=c(1.75, 3, 4.75, 7, 9.75, 13, 16.75, 21, 25.75, 31))

#Set minimum and maximum estimated values of the parameters
Aseq <- seq(from= 0.5, to=1.2, length.out = 50) #Values for A from 0.5 to 1.2 by whatever increments that leads to 50 numbers
Bseq <- seq(from=0.1, to=0.8, length.out = 50) #same for B, from 0.1 to 0.8
Cseq <- seq(from=0.1, to=0.3, length.out = 50) #same for C, from 0.1 to 0.3
FixedA <- 1 #create fixed values for each parameter to keep constant while optimizing another
FixedB <- 0.5
FixedC <- 0.25

InitialParameters <- data.frame(Aseq, Bseq, Cseq)

#Step two. Loop over every value of A, B and C and store SS for each observation as 0

SSAVec <- vector(length=length(Aseq)) #Create empty vectors to store Sum of squeares for changing values in each parameter
SSBVec <- vector(length =length(Bseq))
SSCVec <- vector(length =length(Cseq))


for (i in Aseq) {
  SSAVec[i] <- 0
  SSBVec[i] <- 0
  SSCVec[i] <- 0
}

SSLoopDF <- data.frame(x= rep(Chap5Data$x, each=length(Aseq)), Yobs= rep(Chap5Data$Yobs, each=length(Aseq)), A= rep(Aseq, times=length(Chap5Data$x)), B=rep(Bseq, times=length(Chap5Data$x)), C=rep(Cseq, times=length(Chap5Data$x))) %>% #create dataframe where each value for each parameter interacts with every X 
  mutate(YpredA=A+FixedB*x+FixedC*(x^2), ResA=((Yobs-YpredA)^2),YpredB=FixedA+B*x+FixedC*(x^2), ResB=((Yobs-YpredB)^2), YpredC=FixedA+FixedB*x+C*(x^2), ResC= ((Yobs-YpredC)^2)) %>% #create predicted values over one changing parameter while keeping others constant, and calculates the residuals for each observation 
  group_by(A) %>% #For each parameter value, get the sum of squares from x=1  to x=10
  mutate(SSA = sum(ResA)) %>%
  ungroup() %>%
  group_by(B) %>%
  mutate(SSB=sum(ResB)) %>%
  ungroup %>%
  group_by(C) %>% 
  mutate(SSC = sum(ResC)) %>%
  ungroup()

BestA <- SSLoopDF$A[which.min(SSLoopDF$SSA)] #Find the value for each parameter that minimizes SS
BestB <- SSLoopDF$B[which.min(SSLoopDF$SSB)]
BestC <- SSLoopDF$C[which.min(SSLoopDF$SSC)]

BestA
BestB
BestC
```

##Now, working with every parameter at once (every possible interaction)
```{r pseudocode 5.1 interacting parameters}
InteractAllTheThings <- expand.grid(A=Aseq, B=Bseq, C=Cseq)
SSAllInter <- data.frame(x= rep(Chap5Data$x, each=nrow(InteractAllTheThings)), Yobs= rep(Chap5Data$Yobs, each=nrow(InteractAllTheThings)), A=InteractAllTheThings$A, B=InteractAllTheThings$B, C=InteractAllTheThings$C) %>% #create dataframe with every x and observed y crossed with every possible interaction of A*B*C
  mutate(Ypred=A+B*x+C*(x^2), Res=((Yobs-Ypred)^2)) %>% #get the predicted Y
  group_by(A,B,C) %>% #Group by A, then B, then C to get SS for x=1 to x=10 for every possible combination
  mutate(SS= sum(Res)) %>%
  ungroup()

BestA.int <- SSAllInter$A[which.min(SSAllInter$SS)] 
BestB.int <- SSAllInter$B[which.min(SSAllInter$SS)]
BestC.int <- SSAllInter$C[which.min(SSAllInter$SS)]
#extracts the value for A,B,C that have the lowest SS
BestA.int
BestB.int
BestC.int
```

#Pseudocode 5.2 -> now generate data with process uncertainty

```{r Pseudocode 5.2}
set.seed(1)
A <- BestA
B <- BestB
C <- BestC
X <- seq(1,100,1)
N <- 100
w <- vector(length=length(X))

YpredicDet    <- vector(length=length(X))
YpredicUnc <- vector(length=length(X))

for(i in 1:length(X)){
  w[i] <- runif(n=1, min=-3, max=3) #get random number from the process uncertainty distribution for each observation (same than doing w <- runif(n=length(X), min=-3, max=3))
  YpredicUnc[i] <- A+(B*X[i])+(C*((X[i])^2)) + w[i] #predict y based on x and process ncertainty
  YpredicDet[i]<- A+(B*X[i])+(C*((X[i])^2))
}

UncertainPredictions <- data.frame(X, YpredicDet, YpredicUnc) %>%
  gather(key="model", value="predY", -X) 

ggplot(UncertainPredictions, aes(x=X, y= predY)) +
 geom_line(aes(color=model)) +
coord_cartesian(xlim = c(0,20), ylim=c(0,130))
  #plot both models (zooming in from x=1 to x=150 to be able to spot differences)


```


